title: SemVerName
description: Semanticly Versioned Names Specification http://semvername.org
google_analytics: UA-51498927-1
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
